// Persona presets shared by the PersonaPicker (Token Detail) and the onboarding
// wizard. PERSONA_CAP_DEFAULTS mirrors personas.py PERSONA_DEFINITIONS and is
// used to pre-fill cap values when applying a persona via PATCH so the matrix
// updates in one round-trip. If this drifts from the backend, the backend
// validates each value and the PATCH fails closed.
import type { Persona } from "./types";

export interface PersonaDef {
  key: Persona;
  label: string;
  description: string;
  // wizardOnly personas are shown only in the onboarding wizard's persona step,
  // not in the normal Token Detail persona picker.
  wizardOnly?: boolean;
}

export const PERSONAS: PersonaDef[] = [
  {
    key: "new_user",
    label: "New user (recommended)",
    description: "A safe starting point: the agent can read your home and control the devices you grant it. Locks, alarms, and covers ask for your confirmation. You can change this any time later.",
    wizardOnly: true,
  },
  {
    key: "read_only",
    label: "Read-only observer",
    description: "Reads state, history, logs, templates. No actions, no broadcast.",
  },
  {
    key: "voice_assistant",
    label: "Voice assistant",
    description: "Reads + service calls + broadcast. Locks, alarms, and covers require admin confirmation.",
  },
  {
    key: "automation_builder",
    label: "Automation builder",
    description: "Voice assistant + full discovery (traces, diagnostics) and automation, script, scene, and helper CRUD. Restart and physical actions require confirmation.",
  },
  {
    key: "power_user",
    label: "Power user",
    description: "Full reads and config writes, restart allowed. Physical actions, integrations, dashboards, and backups require confirmation; filesystem and raw YAML stay off.",
  },
  {
    key: "home_admin",
    label: "Home administrator",
    description: "Whole-home control with a safety net. All reads and config writes; restart, physical actions, integrations, dashboards, backups, filesystem, and raw YAML all require admin confirmation.",
  },
  {
    key: "custom",
    label: "Custom",
    description: "Configure each capability individually below.",
  },
];

export const PERSONA_CAP_DEFAULTS: Record<Persona, Record<string, string> | null> = {
  new_user: {
    cap_config_read: "allow",
    cap_template_render: "allow",
    cap_log_read: "deny",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "deny",
    cap_diagnostics: "deny",
    cap_broadcast: "deny",
    cap_service_response: "allow",
    cap_automation_write: "deny",
    cap_script_write: "deny",
    cap_scene_write: "deny",
    cap_helper_write: "deny",
    cap_physical_control: "confirm",
    cap_restart: "deny",
    cap_integration_write: "deny",
    cap_lovelace_write: "deny",
    cap_backup: "deny",
    cap_filesystem: "deny",
    cap_yaml_edit: "deny",
  },
  read_only: {
    cap_config_read: "allow",
    cap_template_render: "allow",
    cap_log_read: "allow",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "allow",
    cap_diagnostics: "allow",
    cap_broadcast: "deny",
    cap_service_response: "allow",
    cap_automation_write: "deny",
    cap_script_write: "deny",
    cap_scene_write: "deny",
    cap_helper_write: "deny",
    cap_physical_control: "deny",
    cap_restart: "deny",
    cap_integration_write: "deny",
    cap_lovelace_write: "deny",
    cap_backup: "deny",
    cap_filesystem: "deny",
    cap_yaml_edit: "deny",
  },
  voice_assistant: {
    cap_config_read: "allow",
    cap_template_render: "allow",
    cap_log_read: "allow",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "deny",
    cap_diagnostics: "deny",
    cap_broadcast: "allow",
    cap_service_response: "allow",
    cap_automation_write: "deny",
    cap_script_write: "deny",
    cap_scene_write: "deny",
    cap_helper_write: "deny",
    cap_physical_control: "confirm",
    cap_restart: "deny",
    cap_integration_write: "deny",
    cap_lovelace_write: "deny",
    cap_backup: "deny",
    cap_filesystem: "deny",
    cap_yaml_edit: "deny",
  },
  automation_builder: {
    cap_config_read: "allow",
    cap_template_render: "allow",
    cap_log_read: "allow",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "allow",
    cap_diagnostics: "allow",
    cap_broadcast: "allow",
    cap_service_response: "allow",
    cap_automation_write: "allow",
    cap_script_write: "allow",
    cap_scene_write: "allow",
    cap_helper_write: "allow",
    cap_physical_control: "confirm",
    cap_restart: "confirm",
    cap_integration_write: "deny",
    cap_lovelace_write: "deny",
    cap_backup: "deny",
    cap_filesystem: "deny",
    cap_yaml_edit: "deny",
  },
  power_user: {
    cap_config_read: "allow",
    cap_template_render: "allow",
    cap_log_read: "allow",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "allow",
    cap_diagnostics: "allow",
    cap_broadcast: "allow",
    cap_service_response: "allow",
    cap_automation_write: "allow",
    cap_script_write: "allow",
    cap_scene_write: "allow",
    cap_helper_write: "allow",
    cap_physical_control: "confirm",
    cap_restart: "allow",
    cap_integration_write: "confirm",
    cap_lovelace_write: "confirm",
    cap_backup: "confirm",
    cap_filesystem: "deny",
    cap_yaml_edit: "deny",
  },
  home_admin: {
    cap_config_read: "allow",
    cap_template_render: "allow",
    cap_log_read: "allow",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "allow",
    cap_diagnostics: "allow",
    cap_broadcast: "allow",
    cap_service_response: "allow",
    cap_automation_write: "allow",
    cap_script_write: "allow",
    cap_scene_write: "allow",
    cap_helper_write: "allow",
    cap_physical_control: "confirm",
    cap_restart: "confirm",
    cap_integration_write: "confirm",
    cap_lovelace_write: "confirm",
    cap_backup: "confirm",
    cap_filesystem: "confirm",
    cap_yaml_edit: "confirm",
  },
  custom: null,
};
